// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1XPvPL7nofcydNcDQArjQS-mmBY1UkI',
    appId: '1:52375665662:web:cad9bcdff30140e90b5eaf',
    messagingSenderId: '52375665662',
    projectId: 'chaeg-92c83',
    authDomain: 'chaeg-92c83.firebaseapp.com',
    storageBucket: 'chaeg-92c83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXK5KsXIwIngoNVAGNfxSaSlVUN8u4AGI',
    appId: '1:52375665662:android:0516dd4220634a3a0b5eaf',
    messagingSenderId: '52375665662',
    projectId: 'chaeg-92c83',
    storageBucket: 'chaeg-92c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjB_p7KEELoTajVOspI4JSR5Xwxn8nm6g',
    appId: '1:52375665662:ios:9dccac61bc8476120b5eaf',
    messagingSenderId: '52375665662',
    projectId: 'chaeg-92c83',
    storageBucket: 'chaeg-92c83.appspot.com',
    iosClientId: '52375665662-adn0tuqjpqbmlhtunacm7dludbfgdrh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjB_p7KEELoTajVOspI4JSR5Xwxn8nm6g',
    appId: '1:52375665662:ios:9dccac61bc8476120b5eaf',
    messagingSenderId: '52375665662',
    projectId: 'chaeg-92c83',
    storageBucket: 'chaeg-92c83.appspot.com',
    iosClientId: '52375665662-adn0tuqjpqbmlhtunacm7dludbfgdrh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaeg',
  );
}
